#!/bin/sh
RESOLV_IPV4="/var/tmp/resolv.conf"
RESOLV_IPV6="/var/tmp/resolv_ipv6.conf"
RESOLV_CONF="/etc/resolv.conf"
DHCP_PD="/var/tmp/dhcp_pd"
DHCP_PD_OLD="/var/tmp/dhcp_pd.old"

echo "$new_domain_name"
echo $new_domain_name
if [ -n "$new_domain_name" -o -n "$new_domain_name_servers" ]; then
	rm -f $RESOLV_IPV6
	
	if [ -n "$new_domain_name_servers" ]; then
		for nameserver in $new_domain_name_servers; do
		   echo nameserver $nameserver >> $RESOLV_IPV6
		done
		#cat $RESOLV_IPV6 >> $RESOLV_CONF
		if [ -n "$new_domain_name" ]; then
			#echo search $new_domain_name >> $RESOLV_IPV6
			#app_sync 1044 act=setdns domain=$new_domain_name dnsserver=$new_domain_name_servers
			if [ -n "$new_ntp_servers" ]; then	
				if [ -f "/var/tmp/ianancc" ]; then
					IA_NA=$(cat "/var/tmp/ianancc")
					if [ -f "/var/tmp/iapdncc" ]; then
						IA_PD=$(cat "/var/tmp/iapdncc")
						echo "get IAPD and IANA snd domain and DNS server and ntp server send to ncc $IA_PD"
						app_sync 1044 0 act=setlan domain="$new_domain_name" dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers" $IA_NA $IA_PD
						echo "app_sync 1044 0 act=setlan domain=$new_domain_name dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers" $IA_NA $IA_PD"
						rm -f /var/tmp/iapdncc
						rm -f /var/tmp/ianancc
						cp $DHCP_PD $DHCP_PD_OLD

					else
					  echo "no IAPD get DNS server and domain and ntp server and IANA  send to ncc "
						app_sync 1044 0 act=setlan domain="$new_domain_name" dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers" $IA_NA
						echo "app_sync 1044 0 act=setlan domain=$new_domain_name dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers" $IA_NA"
						rm -f /var/tmp/ianancc
					fi
				else  
					if [ -f "/var/tmp/iapdncc" ]; then
						IA_PD=$(cat "/var/tmp/iapdncc")
						echo "no IANA get domain and DNS server and ntp server and IAPD  send to ncc "
						app_sync 1044 0 act=setlan domain="$new_domain_name" dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers" $IA_PD
						#echo "app_sync 1044 0 act=setlan domain=$new_domain_name dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers" $IA_PD"
						rm -f /var/tmp/iapdncc
						cp $DHCP_PD $DHCP_PD_OLD
					else
						echo "no IAPD and IANA  send get DNS server and ntp server and domain to ncc "
						app_sync 1044 0 act=setlan domain="$new_domain_name" dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers" 
						#echo "app_sync 1044 0 act=setlan domain=$new_domain_name dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers" "
					fi
				fi
			else
				if [ -f "/var/tmp/ianancc" ]; then
					IA_NA=$(cat "/var/tmp/ianancc")
					if [ -f "/var/tmp/iapdncc" ]; then
						IA_PD=$(cat "/var/tmp/iapdncc")
						echo "get IAPD and IANA snd domain and DNS server send to ncc $IA_PD"
						app_sync 1044 0 act=setlan domain="$new_domain_name" dnsserver="$new_domain_name_servers" $IA_NA $IA_PD
						#echo "app_sync 1044 0 act=setlan domain=$new_domain_name dnsserver="$new_domain_name_servers" $IA_NA $IA_PD"
						rm -f /var/tmp/iapdncc
						rm -f /var/tmp/ianancc
						cp $DHCP_PD $DHCP_PD_OLD

					else
					  echo "no IAPD get DNS server and domain and IANA  send to ncc "
						app_sync 1044 0 act=setlan domain="$new_domain_name" dnsserver="$new_domain_name_servers" $IA_NA
						#echo "app_sync 1044 0 act=setlan domain=$new_domain_name dnsserver="$new_domain_name_servers" $IA_NA"
						rm -f /var/tmp/ianancc
					fi
				else  
					if [ -f "/var/tmp/iapdncc" ]; then
						IA_PD=$(cat "/var/tmp/iapdncc")
						echo "no IANA get domain and DNS server and IAPD  send to ncc "
						app_sync 1044 0 act=setlan domain="$new_domain_name" dnsserver="$new_domain_name_servers" $IA_PD
						#echo "app_sync 1044 0 act=setlan domain=$new_domain_name dnsserver="$new_domain_name_servers" $IA_PD"
						rm -f /var/tmp/iapdncc
						cp $DHCP_PD $DHCP_PD_OLD
					else
						echo "no IAPD and IANA  send get DNS server and domain to ncc "
						app_sync 1044 0 act=setlan domain="$new_domain_name" dnsserver="$new_domain_name_servers" 
						#echo "app_sync 1044 0 act=setlan domain=$new_domain_name dnsserver="$new_domain_name_servers""
					fi
				fi				
			fi
		else
	 	 	echo "no domain"
	 	 	echo $new_domain_name_servers
			#app_sync 1044 0 act=setdns dnsserver="$new_domain_name_servers"
			if [ -n "$new_ntp_servers" ]; then	
				if [ -f "/var/tmp/ianancc" ]; then
					IA_NA=$(cat "/var/tmp/ianancc")
					if [ -f "/var/tmp/iapdncc" ]; then
						IA_PD=$(cat "/var/tmp/iapdncc")
						echo " get IANA and DNS server and and ntp server IAPD  send to ncc "
						#echo	"app_sync 1044 0 act=setlan dnsserver=$new_domain_name_servers sntp="$new_ntp_servers" $IA_NA $IA_PD"
						app_sync 1044 0 act=setlan dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers" $IA_NA $IA_PD
						rm -f /var/tmp/iapdncc
						rm -f /var/tmp/ianancc
						cp $DHCP_PD $DHCP_PD_OLD
					else
						echo "no IApd get DNS server and and ntp server IANA  send to ncc "
						echo "app_sync 1044 0 act=setlan dnsserver=$new_domain_name_servers sntp="$new_ntp_servers" $IA_NA"
						app_sync 1044 0 act=setlan dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers" $IA_NA
						rm -f /var/tmp/ianancc
					fi
				else
					if [ -f "/var/tmp/iapdncc" ]; then
							IA_PD=$(cat "/var/tmp/iapdncc")
							echo "no IANA get DNS server and and ntp server IAPD  send to ncc "
							app_sync 1044 0 act=setlan dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers" $IA_PD
							#echo "app_sync 1044 0 act=setlan dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers" $IA_PD"
							rm -f /var/tmp/iapdncc
							cp $DHCP_PD $DHCP_PD_OLD
					else
						echo "no IApd and IANA get DNS server and ntp server send to ncc "
						echo "app_sync 1044 0 act=setlan dnsserver=$new_domain_name_servers" sntp="$new_ntp_servers"
						app_sync 1044 0 act=setlan dnsserver="$new_domain_name_servers" sntp="$new_ntp_servers"
					fi
					
				fi
			else
				if [ -f "/var/tmp/ianancc" ]; then
					IA_NA=$(cat "/var/tmp/ianancc")
					if [ -f "/var/tmp/iapdncc" ]; then
						IA_PD=$(cat "/var/tmp/iapdncc")
						echo " get IANA and DNS server and IAPD  send to ncc "
						#echo	"app_sync 1044 0 act=setlan dnsserver=$new_domain_name_servers $IA_NA $IA_PD"
						app_sync 1044 0 act=setlan dnsserver="$new_domain_name_servers" $IA_NA $IA_PD
						rm -f /var/tmp/iapdncc
						rm -f /var/tmp/ianancc
						cp $DHCP_PD $DHCP_PD_OLD
					else
						echo "no IApd get DNS server and IANA  send to ncc "
						echo "app_sync 1044 0 act=setlan dnsserver=$new_domain_name_servers $IA_NA"
						app_sync 1044 0 act=setlan dnsserver="$new_domain_name_servers" $IA_NA
						rm -f /var/tmp/ianancc
					fi
				else
					if [ -f "/var/tmp/iapdncc" ]; then
							IA_PD=$(cat "/var/tmp/iapdncc")
							echo "no IANA get DNS server and IAPD  send to ncc "
							app_sync 1044 0 act=setlan dnsserver="$new_domain_name_servers" $IA_PD
							#echo "app_sync 1044 0 act=setlan dnsserver="$new_domain_name_servers" $IA_PD"
							rm -f /var/tmp/iapdncc
							cp $DHCP_PD $DHCP_PD_OLD
					else
						echo "no IApd and IANA get DNS server send to ncc "
						echo "app_sync 1044 0 act=setlan dnsserver=$new_domain_name_servers"
						app_sync 1044 0 act=setlan dnsserver="$new_domain_name_servers"
					fi
					
				fi				
			fi
		fi
	else
		if [ -n "$new_domain_name" ]; then
			#echo search $new_domain_name >> $RESOLV_IPV6
			#app_sync 1044 act=setdns domain=$new_domain_name
			if [ -n "$new_ntp_servers" ]; then	
				if [ -f "/var/tmp/ianancc" ]; then
					IA_NA=$(cat "/var/tmp/ianancc")
					if [ -f "/var/tmp/iapdncc" ]; then
						IA_PD=$(cat "/var/tmp/iapdncc")
						echo "get IAPD and IANA snd domain and ntp server send to ncc $IA_PD"
						app_sync 1044 0 act=setlan domain="$new_domain_name" sntp="$new_ntp_servers" $IA_NA $IA_PD
						echo "app_sync 1044 0 act=setlan domain=$new_domain_name sntp="$new_ntp_servers" $IA_NA $IA_PD"
						rm -f /var/tmp/iapdncc
						rm -f /var/tmp/ianancc
						cp $DHCP_PD $DHCP_PD_OLD

					else
					  echo "no IAPD get domain and ntp server and IANA  send to ncc "
						app_sync 1044 0 act=setlan domain="$new_domain_name" sntp="$new_ntp_servers" $IA_NA
						echo "app_sync 1044 0 act=setlan domain=$new_domain_name sntp="$new_ntp_servers" $IA_NA"
						rm -f /var/tmp/ianancc
					fi
				else  
					if [ -f "/var/tmp/iapdncc" ]; then
						IA_PD=$(cat "/var/tmp/iapdncc")
						echo "no IANA get domain and ntp server and IAPD send to ncc "
						app_sync 1044 0 act=setlan domain="$new_domain_name" sntp="$new_ntp_servers" $IA_PD
						#echo "app_sync 1044 0 act=setlan domain=$new_domain_name sntp="$new_ntp_servers" $IA_PD"
						rm -f /var/tmp/iapdncc
						cp $DHCP_PD $DHCP_PD_OLD
					else
						echo "no IAPD and IANA  send get ntp server and domain to ncc "
						app_sync 1044 0 act=setlan domain="$new_domain_name" sntp="$new_ntp_servers" 
						#echo "app_sync 1044 0 act=setlan domain=$new_domain_name sntp="$new_ntp_servers" "
					fi
				fi
			else
				if [ -f "/var/tmp/ianancc" ]; then
					IA_NA=$(cat "/var/tmp/ianancc")
					if [ -f "/var/tmp/iapdncc" ]; then
						IA_PD=$(cat "/var/tmp/iapdncc")
						echo "get IAPD and IANA snd domain send to ncc $IA_PD"
						app_sync 1044 0 act=setlan domain="$new_domain_name" $IA_NA $IA_PD
						#echo "app_sync 1044 0 act=setlan domain=$new_domain_name $IA_NA $IA_PD"
						rm -f /var/tmp/iapdncc
						rm -f /var/tmp/ianancc
						cp $DHCP_PD $DHCP_PD_OLD

					else
					  echo "no IAPD get domain and IANA  send to ncc "
						app_sync 1044 0 act=setlan domain="$new_domain_name" $IA_NA
						#echo "app_sync 1044 0 act=setlan domain=$new_domain_name $IA_NA"
						rm -f /var/tmp/ianancc
					fi
				else  
					if [ -f "/var/tmp/iapdncc" ]; then
						IA_PD=$(cat "/var/tmp/iapdncc")
						echo "no IANA get domain and IAPD  send to ncc "
						app_sync 1044 0 act=setlan domain="$new_domain_name" $IA_PD
						#echo "app_sync 1044 0 act=setlan domain=$new_domain_name $IA_PD"
						rm -f /var/tmp/iapdncc
						cp $DHCP_PD $DHCP_PD_OLD
					else
						echo "no IAPD and IANA  send get domain to ncc "
						app_sync 1044 0 act=setlan domain="$new_domain_name" 
						#echo "app_sync 1044 0 act=setlan domain=$new_domain_name"
					fi
				fi				
			fi
		fi	
	fi
else
	if [ -f "/var/tmp/ianancc" ]; then
			IA_NA=$(cat "/var/tmp/ianancc")
			
		if [ -f "/var/tmp/iapdncc" ]; then
			IA_PD=$(cat "/var/tmp/iapdncc")
		echo "get IAPD send to ncc $IA_PD"
			app_sync 1044 0 act=setlan $IA_NA $IA_PD
			echo "app_sync 1044 0 act=setlan $IA_NA $IA_PD"
			rm -f /var/tmp/iapdncc
			rm -f /var/tmp/ianancc
			cp $DHCP_PD $DHCP_PD_OLD

		else
			echo "get IANA send to ncc $IA_NA"
			app_sync 1044 0 act=setlan $IA_NA
			echo "app_sync 1044 0 act=setlan $IA_NA"
			rm -f /var/tmp/ianancc
		fi
		
	else
		if [ -f "/var/tmp/iapdncc" ]; then
			IA_PD=$(cat "/var/tmp/iapdncc")
			echo "get IAPD send to ncc $IA_PD"
			app_sync 1044 0 act=setlan $IA_PD
			echo "app_sync 1044 0 act=setlan $IA_PD"
			rm -f /var/tmp/iapdncc
			cp $DHCP_PD $DHCP_PD_OLD

		fi
	fi
fi



if [ -f "/var/tmp/ianancc" ]; then
	IA_NA=$(cat "/var/tmp/ianancc")
	
	echo "get IANA send to ncc $IA_NA"
	app_sync 1044 0 $IA_NA
	rm -f /var/tmp/ianancc
fi

if [ -n "$new_aftr_name" ]; then
	echo "script AFTR $new_aftr_name"
	sleep 2
	app_sync 1044 0 act=setdslite aftr="$new_aftr_name"
fi