#!/bin/sh

ifconfig lo 127.0.0.1

USE_SAMBA=0
CINIT=1

hostname trendnetrouter

mount -t proc proc /proc
mount -t ramfs ramfs /var
mount -t ramfs ramfs /fw
mount -t sysfs sysfs /sys
mount -t jffs2 /dev/mtdblock2 /flash

mkdir /var/tmp
mkdir /var/tmp/pts
mkdir /var/web
mkdir /var/log
mkdir /var/run
mkdir /var/lock
mkdir /var/system
mkdir /var/dnrd
mkdir /var/lib
mkdir /var/lib/misc
##For pptp
mkdir /var/ppp
mkdir /var/ppp/peers
mkdir /var/wps

mount -t devpts /dev/pts /dev/pts

cp -af /bin/fwUpgrade /var/tmp/

##For miniigd
if [ -f "/bin/miniigd" ]; then
mkdir -p /var/linuxigd
cp /etc/tmp/pics* /var/linuxigd 2>/dev/null
fi

#for shell login
cp -f /etc/tmp/passwd /var/tmp/passwd 2>/dev/null
chmod -R 777 /fw
chmod -R 750 /var

passwd root -p "cameorouter" 2>/dev/null
 
 
# for wireless client mode 802.1x
mkdir /var/1x
cp -rf /usr/1x/* /var/1x/ 2>/dev/null
 
 
# modify dst-cache setting
echo "4096" > /proc/sys/net/ipv4/route/max_size
echo "180" > /proc/sys/net/ipv4/route/gc_thresh
echo 1 > /proc/sys/net/ipv4/route/gc_elasticity
echo 35 > /proc/sys/net/ipv4/route/gc_interval
echo 60 > /proc/sys/net/ipv4/route/secret_interval
echo 10 > /proc/sys/net/ipv4/route/gc_timeout
 
echo "4096" > /proc/sys/net/netfilter/nf_conntrack_max
echo "600" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_established
echo "20" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_time_wait
echo "20" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_close
echo "80" > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout
echo "90" > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout_stream
echo "90" > /proc/sys/net/ipv4/netfilter/ip_conntrack_generic_timeout
echo "1048576" > /proc/sys/net/ipv4/rt_cache_rebuild_count
echo "32" > /proc/sys/net/netfilter/nf_conntrack_expect_max
#leo add for kernel security
echo 1 > /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses
echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter
echo 3 > /proc/sys/net/ipv4/tcp_retries1
echo 60 > /proc/sys/net/ipv4/tcp_fin_timeout
echo 7200 > /proc/sys/net/ipv4/tcp_keepalive_time
echo 1 > /proc/sys/net/ipv4/tcp_window_scaling
echo 1 > /proc/sys/net/ipv4/tcp_sack
echo 1 > /proc/sys/net/ipv4/tcp_timestamps
# disable TCP flag ECN and CWR
echo 0 > /proc/sys/net/ipv4/tcp_ecn


#init fastnat
echo 1 > /proc/fast_nat
echo 0 > /proc/qos
#init sw
echo 0 > /proc/rtk_vlan_support

# set kthreadd high priority for performance
renice -10 2
# set ksoftirqd high priority for performance
renice -10 3


#echo 2048 > /proc/sys/net/core/hot_list_length

# language pack
if [ -f "/flash/lang.js" ]; then
	echo "language pack exists"
else
	echo "language pack not found"
	ln -s /www/def_lang.js /flash/lang.js
fi
ln -s /flash/lang.js /var/tmp/lang.js

# CSS Check
if [ -f "/var/tmp/style.css" ]; then
	echo "style.css exists"
else
	echo "style.css not found"
	ln -s /www/def-style.css /var/tmp/style.css
fi

#start ncc
ncc
